library(data.table)
library(readxl)
EastWestAirlines <- read_xlsx("C:/Users/Susheel/Desktop/clusters/EastWestAirlines.xlsx", sheet = "data")
View(EastWestAirlines)
colnames(EastWestAirlines)
ncol(EastWestAirlines)
sub_EastWestAirlines <- EastWestAirlines[,2:12]
norm_airline <- scale(sub_EastWestAirlines)
distanct_airline <- dist(norm_airline,method="euclidean")
str(distanct_airline)
airline_clust <- hclust(distanct_airline, method = "complete")
group_airline <- cutree(airline_clust,k=5)
EastWestAirlines_New1 <- cbind(EastWestAirlines, group_airline)
setnames(EastWestAirlines_New1, 'group_airline', 'group_hclust')
aggregate(EastWestAirlines_New1[,2:12],by= list(EastWestAirlines_New1$group_hclust), FUN = mean)
airline_kmeans <- kmeans(norm_airline,5)
str(airline_kmeans)
airline_kmeans$centers
EastWestAirlines_New1 <- cbind(EastWestAirlines_New1, airline_kmeans$cluster)
colnames(EastWestAirlines_New1)
library(cluster)
xcl <- clara(norm_airline,5)
clusplot(xcl)
xpm <- pam(norm_airline,5)
clusplot(xpm)
aggregate(EastWestAirlines_New1[,2:12],by= list(EastWestAirlines_New1$`airline_kmeans$cluster`), FUN = mean)